// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"test-server/internal/api/restapi/models"
)

// CreateAPIKeyReader is a Reader for the CreateAPIKey structure.
type CreateAPIKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAPIKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAPIKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateAPIKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateAPIKeyOK creates a CreateAPIKeyOK with default headers values
func NewCreateAPIKeyOK() *CreateAPIKeyOK {
	return &CreateAPIKeyOK{}
}

/* CreateAPIKeyOK describes a response with status code 200, with default header values.

Ok
*/
type CreateAPIKeyOK struct {
	Payload *models.UUID
}

func (o *CreateAPIKeyOK) Error() string {
	return fmt.Sprintf("[POST /create-api-key][%d] createApiKeyOK  %+v", 200, o.Payload)
}
func (o *CreateAPIKeyOK) GetPayload() *models.UUID {
	return o.Payload
}

func (o *CreateAPIKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UUID)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAPIKeyDefault creates a CreateAPIKeyDefault with default headers values
func NewCreateAPIKeyDefault(code int) *CreateAPIKeyDefault {
	return &CreateAPIKeyDefault{
		_statusCode: code,
	}
}

/* CreateAPIKeyDefault describes a response with status code -1, with default header values.

error
*/
type CreateAPIKeyDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create Api key default response
func (o *CreateAPIKeyDefault) Code() int {
	return o._statusCode
}

func (o *CreateAPIKeyDefault) Error() string {
	return fmt.Sprintf("[POST /create-api-key][%d] createApiKey default  %+v", o._statusCode, o.Payload)
}
func (o *CreateAPIKeyDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateAPIKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
