// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SetAPIKeyHandlerFunc turns a function with the right signature into a set Api key handler
type SetAPIKeyHandlerFunc func(SetAPIKeyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SetAPIKeyHandlerFunc) Handle(params SetAPIKeyParams) middleware.Responder {
	return fn(params)
}

// SetAPIKeyHandler interface for that can handle valid set Api key params
type SetAPIKeyHandler interface {
	Handle(SetAPIKeyParams) middleware.Responder
}

// NewSetAPIKey creates a new http.Handler for the set Api key operation
func NewSetAPIKey(ctx *middleware.Context, handler SetAPIKeyHandler) *SetAPIKey {
	return &SetAPIKey{Context: ctx, Handler: handler}
}

/* SetAPIKey swagger:route POST /set-api-key setApiKey

SetAPIKey set Api key API

*/
type SetAPIKey struct {
	Context *middleware.Context
	Handler SetAPIKeyHandler
}

func (o *SetAPIKey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSetAPIKeyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
