// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateAPIKeyHandlerFunc turns a function with the right signature into a create Api key handler
type CreateAPIKeyHandlerFunc func(CreateAPIKeyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateAPIKeyHandlerFunc) Handle(params CreateAPIKeyParams) middleware.Responder {
	return fn(params)
}

// CreateAPIKeyHandler interface for that can handle valid create Api key params
type CreateAPIKeyHandler interface {
	Handle(CreateAPIKeyParams) middleware.Responder
}

// NewCreateAPIKey creates a new http.Handler for the create Api key operation
func NewCreateAPIKey(ctx *middleware.Context, handler CreateAPIKeyHandler) *CreateAPIKey {
	return &CreateAPIKey{Context: ctx, Handler: handler}
}

/* CreateAPIKey swagger:route POST /create-api-key createApiKey

CreateAPIKey create Api key API

*/
type CreateAPIKey struct {
	Context *middleware.Context
	Handler CreateAPIKeyHandler
}

func (o *CreateAPIKey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateAPIKeyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
