// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"test-server/internal/api/restapi/models"
)

// CreateAPIKeyOKCode is the HTTP code returned for type CreateAPIKeyOK
const CreateAPIKeyOKCode int = 200

/*CreateAPIKeyOK Ok

swagger:response createApiKeyOK
*/
type CreateAPIKeyOK struct {

	/*
	  In: Body
	*/
	Payload *models.UUID `json:"body,omitempty"`
}

// NewCreateAPIKeyOK creates CreateAPIKeyOK with default headers values
func NewCreateAPIKeyOK() *CreateAPIKeyOK {

	return &CreateAPIKeyOK{}
}

// WithPayload adds the payload to the create Api key o k response
func (o *CreateAPIKeyOK) WithPayload(payload *models.UUID) *CreateAPIKeyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Api key o k response
func (o *CreateAPIKeyOK) SetPayload(payload *models.UUID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAPIKeyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateAPIKeyDefault error

swagger:response createApiKeyDefault
*/
type CreateAPIKeyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAPIKeyDefault creates CreateAPIKeyDefault with default headers values
func NewCreateAPIKeyDefault(code int) *CreateAPIKeyDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateAPIKeyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create Api key default response
func (o *CreateAPIKeyDefault) WithStatusCode(code int) *CreateAPIKeyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create Api key default response
func (o *CreateAPIKeyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create Api key default response
func (o *CreateAPIKeyDefault) WithPayload(payload *models.Error) *CreateAPIKeyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Api key default response
func (o *CreateAPIKeyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAPIKeyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
