// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"test-client/internal/api/restapi/models"
)

// SendMessageReader is a Reader for the SendMessage structure.
type SendMessageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendMessageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSendMessageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSendMessageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSendMessageOK creates a SendMessageOK with default headers values
func NewSendMessageOK() *SendMessageOK {
	return &SendMessageOK{}
}

/* SendMessageOK describes a response with status code 200, with default header values.

Ok
*/
type SendMessageOK struct {
}

func (o *SendMessageOK) Error() string {
	return fmt.Sprintf("[POST /send-message][%d] sendMessageOK ", 200)
}

func (o *SendMessageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSendMessageDefault creates a SendMessageDefault with default headers values
func NewSendMessageDefault(code int) *SendMessageDefault {
	return &SendMessageDefault{
		_statusCode: code,
	}
}

/* SendMessageDefault describes a response with status code -1, with default header values.

error
*/
type SendMessageDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the send message default response
func (o *SendMessageDefault) Code() int {
	return o._statusCode
}

func (o *SendMessageDefault) Error() string {
	return fmt.Sprintf("[POST /send-message][%d] sendMessage default  %+v", o._statusCode, o.Payload)
}
func (o *SendMessageDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *SendMessageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
