// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"test-client/internal/api/restapi/models"
)

// NewSetAPIKeyParams creates a new SetAPIKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetAPIKeyParams() *SetAPIKeyParams {
	return &SetAPIKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetAPIKeyParamsWithTimeout creates a new SetAPIKeyParams object
// with the ability to set a timeout on a request.
func NewSetAPIKeyParamsWithTimeout(timeout time.Duration) *SetAPIKeyParams {
	return &SetAPIKeyParams{
		timeout: timeout,
	}
}

// NewSetAPIKeyParamsWithContext creates a new SetAPIKeyParams object
// with the ability to set a context for a request.
func NewSetAPIKeyParamsWithContext(ctx context.Context) *SetAPIKeyParams {
	return &SetAPIKeyParams{
		Context: ctx,
	}
}

// NewSetAPIKeyParamsWithHTTPClient creates a new SetAPIKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetAPIKeyParamsWithHTTPClient(client *http.Client) *SetAPIKeyParams {
	return &SetAPIKeyParams{
		HTTPClient: client,
	}
}

/* SetAPIKeyParams contains all the parameters to send to the API endpoint
   for the set Api key operation.

   Typically these are written to a http.Request.
*/
type SetAPIKeyParams struct {

	// Body.
	Body *models.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set Api key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetAPIKeyParams) WithDefaults() *SetAPIKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set Api key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetAPIKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set Api key params
func (o *SetAPIKeyParams) WithTimeout(timeout time.Duration) *SetAPIKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set Api key params
func (o *SetAPIKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set Api key params
func (o *SetAPIKeyParams) WithContext(ctx context.Context) *SetAPIKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set Api key params
func (o *SetAPIKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set Api key params
func (o *SetAPIKeyParams) WithHTTPClient(client *http.Client) *SetAPIKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set Api key params
func (o *SetAPIKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set Api key params
func (o *SetAPIKeyParams) WithBody(body *models.UUID) *SetAPIKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set Api key params
func (o *SetAPIKeyParams) SetBody(body *models.UUID) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SetAPIKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
