// Code generated by go-swagger; DO NOT EDIT.

// Package restapi test-client
//
//  test grpc client
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
